abstract class StringConstants {
  static const String kToolKitX = 'ToolKit X';
  static const String kAppIntroduction =
      'Workforce management designed \n to enhance efficiency, productivity \n and safety';
  static const String kAppIntroductionNoSpacing =
      'Workforce management designed to enhance efficiency, productivity and safety';
  static const String kWelcomeToToolkitX = 'Welcome to ToolKitX';
  static const String kStartNow = 'START NOW';
  static const String kSelectTimeZone = 'Select Your TimeZone';
  static const String kEmailAddress = 'Email Address';
  static const String kPassword = 'Password'; //
  static const String kNoWorkOrder = 'No workorder!'; //
  static const String kNoChecklist = 'No checklist!'; //
  static const String kNoLogs = 'No logs!'; //
  static const String kNoLoto = 'No loto!'; //
  static const String kNoPermit = 'No permit!'; //
  static const String kNoDocuments = 'No documents!'; //
  static const String kNoParts = 'No items/parts!'; //
  static const String kParts = 'Parts'; //
  static const String kNoMisCost = 'No Misc.Cost!'; //
  static const String kNoDowntown = 'No downtime!'; //
  static const String kSelectType = 'Select type'; //
  static const String kSelectTypeValidation = 'Please Select type'; //
  static const String kSafetyNoticeIssue =
      'Do you want to issue this notice?'; //
  static const String kSelectCompany = 'Select Company'; //
  static const String kNext = 'NEXT';
  static const String kLogin = 'LOGIN';
  static const String kWelcome = 'Welcome';
  static const String kPlannedQuantity = "Planned Quantity: ";
  static const String kCamera = 'Camera';
  static const String kOther = 'Other';
  static const String kDevice = 'Device';
  static const String kUploadFrom = 'Upload From';
  static const String kEnterReason = 'Enter Reason';
  static const String kType = 'Type';
  static const String kGenerateOtp = 'GENERATE OTP';
  static const String kSubmit = 'Submit';
  static const String kLoadMore = 'Load more...';
  static const String kNoMoreData = 'No more data!';
  static const String kAddMore = 'Add More';
  static const String kDelete = 'Delete';
  static const String kAddImages = 'Add Images/Comment';
  static const String kErrorImageUpload =
      'Cannot upload image! Please try again!';
  static const String kErrorPickImage = 'Failed to pick image';
  static const String kAddTodo = 'Add ToDo';
  static const String kDeleteImage =
      'Are you sure you want to delete the image?';
  static const String kDraft = 'Draft';
  static const String kSaveDraft = 'Save Draft';
  static const String kNotAccepted = 'Not Accepted';
  static const String kOverdue = 'Overdue';
  static const String kSubmitted = 'Submitted';
  static const String kUploadPhoto = 'Upload Photo';
  static const String kAddCommentImage = 'Add Comment/Image';
  static const String kHint = 'Hint';
  static const String kSelectComment = 'Please enter comment!';
  static const String kSelectReason = 'Please select a reason';
  static const String kChecklistNotEditable =
      'After submitting you will not be able to edit the checklist again.';
  static const String kFailedToCaptureImage = 'Failed to capture image';
  static const String kCustomFieldInfo = 'Custom field info';
  static const String kCustomField = 'Custom Field';
  static const String kViewCustomField = 'Tap to view custom field info';
  static const String kComment = 'Comment';
  static const String kViewComment = 'Tap to view comment';
  static const String kPermissionsDenied =
      'Permissions are permanently denied. Please provide permission through setting.';
  static const String kEnterNewPassword =
      'Enter New Password'; // comment lines indicates that keys are not available
  static const String kConfirmPassword = 'Confirm Password'; //
  static const String kNoCustomFields = 'No custom fields info!'; //
  static const String kNoDocument = 'No Document!'; //
  static const String kNoToDoAssignedBy = 'No todo is assigned by you!'; //
  static const String kNoToDoAssignedTo = 'No todo is assigned to you!'; //
  static const String kNoComment = 'No comments!'; //
  static const String kNoInjuredPerson = 'No injured person!'; //
  static const String kNoILinkedPermit = 'No linked permit!'; //
  static const String kSelectDueDate = 'Please select due date!'; //
  static const String kAddHeading = 'Please add heading!'; //
  static const String kAddDescription = 'Please add description!'; //
  static const String kAssignedToMe = 'assignedtome'; //
  static const String kSelect = 'Select'; //
  static const String kAssignedByMe = 'assignedbyme'; //
  static const String kViewHistory = 'View History'; //
  static const String kDocumentNameValidation =
      'Please enter document name!'; //
  static const String kDocumentUploadValidation =
      'Please add atleast one photo!'; //
  static const String kApplyFilter = 'Apply Filter'; //
  static const String kLeaveDetails = 'Leave Details'; //
  static const String kStartDateValidation = 'Please select start date!'; //
  static const String kEndDateValidation = 'Please select end date!'; //
  static const String kTypeValidation = 'Please select type!'; //
  static const String kReasonValidation = 'Please enter reason!'; //
  static const String kEmergencyContactValidation =
      'Please enter emergency contact!'; //
  static const String kAlert = 'Alert'; //
  static const String kViewAll = 'View All'; //
  static const String kCannotUnlinkPermit = 'Cannot unlink permit!';
  static const String kFiles = 'Files';
  static const String kOtpGenerated = 'OTP generated';
  static const String kSelectDateFormat = 'Select Your Date Format';
  static const String kSave = 'SAVE';
  static const String kValueB = 'Value B: ';
  static const String kValueA = 'Value A: ';
  static const String kNoDatesScheduled =
      'No dates scheduled for this checklist!';
  static const String kNoHeader =
      'No header data available for this checklist!';
  static const String kOldPassword = 'Old Password'; //
  static const String kToDoHistory = 'ToDo History'; //
  static const String kEnterOtp = 'Enter OTP'; //
  static const String kAllDataLoaded = 'All Data Loaded'; //
  static const String kSelectCategory = 'Select category'; //
  static const String kSelectVendor = 'Select vendor'; //
  static const String kSelectCurrency = 'Select currency'; //
  static const String kResolve = 'Resolve'; //
  static const String kSelectYourLanguage = 'Select Your Language';
  static const String kClearFilter = 'Clear';
  static const String kPleaseConfirm = 'Please Confirm';
  static const String kThirdParty = 'Third Party Approve';
  static const String kEditHeader = 'Edit Header';
  static const String kResponseDate = 'Response Date:';
  static const String kNoResponseFound = 'No response found!';
  static const String kReject = 'Reject'; //
  static const String kSelectCreatedFor = 'Please select created for!'; //
  static const String kDialogContent =
      "The language file doesn't exist or an old version.Please download the latest language file."; //
  static const String kReload = 'RELOAD'; //
  static const String kDownloadPdf = 'Pdf';
  static const String kOk = 'Ok';
  static const String kNo = 'No';
  static const String kApprovalPending = 'Approval Pending';
  static const String kLastUploaded = 'Last Uploaded : ';
  static const String kViewCertificate = 'View Certificate : ';
  static const String kUploadNewCertificate = 'Upload new Certificate : ';
  static const String kPendingSelectedCertificate =
      "You can't upload new certificate as approval is pending for selected certificate";
  static const String kDateFormatValidate = 'Please select a Date Format!'; //
  static const String kChangePassword = 'Change Password'; //
  static const String kChangeLanguage = 'Change Language';
  static const String kChangeTimezone = 'Change Timezone';
  static const String kChangeDateFormat = 'Change DateFormat';
  static const String kPrivacyPolicyUrl =
      'https://www.toolkitx.com/privacypolicy.html';
  static const String kMaturityModelUrl =
      'https://www.toolkitx.com/campaign/permit-to-work/';
  static const String kToolkitXEmail = 'info@toolkit.com';
  static const String kSelectBloodGroup = 'Select Blood Group'; //
  static const String kSignature = 'Signature';
  static const String kEditSignature = 'Edit Signature';
  static const String kSignatureNotFound = 'Signature Not Found';
  static const String kUpload = 'Upload';
  static const String kChecklist = 'Checklist';
  static const String kFilters = 'Filters';
  static const String kChecklistName = 'Checklist Name';
  static const String kApply = 'Apply';
  static const String kComments = 'Comments';
  static const String kCategory = 'Category';
  static const String kRemove = 'Remove';
  static const String kApprove = 'Approve';
  static const String kChangeRole = 'Change Role';
  static const String kFirstNameValidate = 'Please add first name!';
  static const String kLastNameValidate = 'Please add last name!';
  static const String kContactValidate = 'Please add contact number!';
  static const String kLogoutDialogContent =
      'Are you sure you want to log out?';
  static const String kNoInternetMessage =
      'Oops! Please ensure your device is connected to the internet to access rest of the module'; //
  static const String kReportAnIncident = 'Report an Incident';
  static const String kDateRange = 'Date Range';
  static const String kSelectDate = 'Select Date';
  static const String kBis = 'bis';
  static const String kStatus = 'Status';
  static const String kSelectStatus = 'Select Status';
  static const String kDone = 'Done';
  static const String kSelectCategoryIncident = 'Select category of incident';
  static const String kReportNewIncident = 'Report new incident';
  static const String kReportAnonymously = 'Report Anonymously';
  static const String kContractor = 'Contractor';
  static const String kDateOfIncident = 'Date of incident';
  static const String kTime = 'Time';
  static const String kSelectTime = 'Select Time';
  static const String kDetailedDescription = 'Detailed description of facts';
  static const String kPhoto = 'Photo';
  static const String kSelectContractor = 'Select Contractor';
  static const String kSite = 'Site';
  static const String kResponded = 'Responded';
  static const String kLocation = 'Location';
  static const String kWorkforce = 'Workforce';
  static const String kTeam = 'Teams';
  static const String kSystemUser = 'System User';
  static const String kAssignedFor = 'Assigned for: ';
  static const String kReportToAuthorities = 'Report to authorities';
  static const String kSelectSite = 'Select Site';
  static const String kSelectLocation = 'Select Location';
  static const String kSelectLanguageAgain = 'Please select language again'; //
  static const String kTryAgainInSomeTime = 'Try again in some time'; //
  static const String kOtpUnsuccessful = 'OTP generation was Unsuccessful!'; //
  static const String kInitializingLanguage = 'Initializing Language...'; //
  static const String kValidateEmptyEmail = 'Please enter email'; //
  static const String kValidateEmptyPassword = 'Please enter password';
  static const String kSelectUserTypeValidation = 'Please select a type'; //
  static const String kSearch = 'Search'; //
  static const String kRefresh = 'Refresh'; //
  static const String kNoData = 'No data!'; //
  static const String kSubmitTodo = 'Submit TODO'; //
  static const String kSafetyNoticeValidation = 'Please enter notice!'; //
  static const String kSafetyNoticeValidityValidation =
      'Please enter validity!'; //
  static const String kUploadFiles = 'Uploading files...'; //
  static const String kDate = 'Date'; //
  static const String kSubmitTodoPopUp = 'Do you want to submit todo?'; //
  static const String kDescriptionValidation =
      'Description cannot be empty.'; //
  static const String kEventDateValidation = 'Event date cannot be empty.'; //
  static const String kEventTimeValidation = 'Event time cannot be empty.'; //
  static const String kSomethingWentWrong = 'Something went wrong';
  static const String kNoInternetError =
      'We could not load the information. Please\ncheck the internet connection and refresh\nthis screen so we can synchronize the data.'; //
  static const String kValidatePassword = 'Please enter old password/opt';
  static const String kValidateNewPassword = 'Please enter a new password';
  static const String kValidateConfirmPassword =
      'Please enter confirm password';
  static const String kValidatePasswordMatch = 'Passwords must match!';
  static const String kNoRecordsFound = 'No records found!';
  static const String kSearchLanguage = 'Search language';
  static const String kSearchTimezone = 'Search timezone';
  static const String kSearchPartName = 'Search Part Name...';
  static const String kPermitType = 'Permit Type';
  static const String kEmergency = 'Emergency';
  static const String kKeywords = 'Keywords';
  static const String kFilter = 'Filter';
  static const String kGeneratePdf = 'Generate PDF';
  static const String kClosePermit = 'Close Permit';
  static const String kOpenPermit = 'Open Permit';
  static const String kRequestPermit = 'Request Permit';
  static const String kPermitNo = 'Permit No';
  static const String kKeySafeNo = 'Key Safe No';
  static const String kKeySafeKeyNo = 'Key Safe Key No';
  static const String kEarthingScheduleNo = 'Earthing Schedule No';
  static const String kSelectedPersonReport = 'Selected Person Report';
  static const String kPortableDrainEarth = 'Portable Drain Earth';
  static const String kCircuitIdentificationFlag =
      'Circuit Identification Flag';
  static const String kCircuitIdentificationWristlets =
      'Circuit Identification Wristlets';
  static const String kSingleLineDiagram = 'Single Line Diagram';
  static const String kPID = 'P&ID';
  static const String kControlPerson = 'Control Person(s)';
  static const String kCLOSEPERMIT = 'CLOSE PERMIT';
  static const String kOPENPERMIT = 'OPEN PERMIT';
  static const String kNoRecordsFilter = 'No records found for these filters';
  static const String kDiscardChanges = 'Discard Changes?';
  static const String kAppVersion = 'App version';
  static const String kWorkforceAssigned = 'Workforce Assigned';
  static const String kWorkforceRemoved = 'Workforce Removed';
  static const String kCancel = 'Cancel';
  static const String kDiscard = 'Discard';
  static const String k1 = '1';
  static const String kQ = 'Q';
  static const String kTopic = 'Topic';
  static const String kQuiz = 'Quiz';
  static const String kDownload = 'Download';
  static const String kStartDate = 'Start Date'; //
  static const String kSelectPriority = 'Select Priority'; //
  static const String kNotAvailable = 'Not Available';
  static const String kExpiryDate = 'Expiry Date';
  static const String kStartCourse = 'Start Course';
  static const String kFeedback = 'Feedback';
  static const String kSkip = 'Skip';
  static const String kSaveAndNext = 'Save and Next';
  static const String kSaveAnswer = 'Save Answer';
  static const String kAnswerSaved = "Answer Saved";
  static const String kAnswerNotSaved =
      "Couldn't Save your answer, Please try Again!";
  static const String kStartQuiz = 'Start Quiz';
  static const String kFinishQuiz = 'Finish Quiz';
  static const String kQuizSubmitted = "Quiz Submitted";
  static const String kQuizSubmittingError =
      "Your Quiz is not submitted, please try again!";
  static const String kSubmitQuiz = 'Submit Quiz';
  static const String kSureToSubmitTheQuiz = 'Are you sure to submit the quiz?';
  static const String kMarks = 'Marks';
  static const String kPagesInside = 'Pages inside';
  static const String kQuestionsInside = 'Questions inside';
  static const String kNameValidation = 'Please enter name';
  static const String kSelectPermits = 'Select Permits';
  static const String kAddLinkToPermit = 'Add Link To Permit';
  static const String kSignInHere = 'Sign in here';
  static const String kGettingStarted = "Getting Started";
  static const String kUploadCertificate = 'Upload Certificate';
  static const String kCertificateUploaded = 'Certificate Uploaded ';
  static const String kFillAllDetails =
      'Please select start date, expiry date and valid certificate copy to continue';
  static const String kPermitAssigned = 'Permit assigned to you';
  static const String kPermitError = 'Permit assigning error';
  static const String kWorkOrderAssigned = 'Work Order assigned to you';
  static const String kWorkOrderError = 'Work Order assigning error';
  static const String kLOTOAssigned = 'LOTO assigned to you';
  static const String kLOTOError = 'LOTO assigning error';
  static const String kChecklistAssigned = 'Checklist assigned to you';
  static const String kSelectOrigination = 'Select origination'; //
  static const String kSelectCostCenter = 'Select Cost Center'; //
  static const String kMiscCostValidation = 'Please enter all data'; //
  static const String kPlannedDateValidation =
      "Planned finished date can't be greater than planned start date!"; //
  static const String kChecklistError = 'Checklist assigning error';
  static const String kSignInError = 'Invalid Data';
  static const String kWarning = 'Warning';
  static const String kCapture = 'Capture';
  static const String kQRError = 'Invalid Location';
  static const String kLotoStarted = "Loto Started";
  static const String kPhotosUploaded = "Photos Uploaded";
  static const String kLotoCommentSaved = "Loto Comment saved";
  static const String kLotoRemoveStarted = "Loto Remove Started";
  static const String kLotoApplied = "Loto Applied";
  static const String kLotoAccepted = "Loto Approved";
  static const String kLotoRemoved = "Loto Removed";
  static const String kPleaseVerifyEverything =
      "Please verify everything before performing this action";
  static const String kLocationDocuments = "Location Documents";
  static const String kLoginSuccess = 'Logged in Successfully';
  static const String kConfirmAssetWithQR = "Confirm Asset with QRCode";
  static const String kUnauthorized =
      'You are not authorized to access the location. Do you still want to continue ? ';
  static const String kUnauthorizedError = 'oops we got unknown error';
  static const String kYouHaveCoursesToComplete =
      'You have 1 courses to complete this certificate, keep it up!';
  static const String kNoFiles = 'No Files found!';
  static const String kAssetName = "Asset Name";
  static const String kAssetTag = "Asset Tag";
  static const String kServiceSite = "Service Site";
  static const String kAssetGroup = "Asset Group";
  static const String kCritically = "Critically";
  static const String kParentAsset = "Parent Asset";
  static const String kPosition = "Position";
  static const String kPriority = "Priority";
  static const String kState = "State";
  static const String kAssetSpecialist = "Asset Specialist";
  static const String kBarcode = "Barcode";
  static const String kSerial = "Serial#";
  static const String kModel = "Model";
  static const String kITInfo = "IT Info:";
  static const String kITType = "IT Type";
  static const String kITFlag = "IT Flag";
  static const String kIP = "IP";
  static const String kOtherIp = "Other IP";
  static const String kMACAddress = "MAC Address";
  static const String kSubType = "Sub Type";
  static const String kOSName = "OS Name";
  static const String kSystemID = "System ID";
  static const String kLinkedTo = "Linked To";
  static const String kExtId = "Ext.Id";
  static const String kWarranty = "Warranty:";
  static const String kCodes = "Codes:";
  static const String kLatitude = "Latitude";
  static const String kAccount = "Account";
  static const String kDepartment = "Department";
  static const String kLongitude = "Longitude";
  static const String kWarrantyStart = "WarrantyStart";
  static const String kWarrantyEnd = "Warranty End";
  static const String kNoLinkedDoc = 'No Linked Documents!';
}
