name: toolkit
description: ToolKitX is the latest end-to-end Software as a Service (SaaS) solution for field workforce management. We drive our customer's success by simplifying, automating and digitalizing their environment.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  intl: ^0.18.1
  get_it: ^7.6.7
  shimmer: ^3.0.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  sqflite: ^2.3.2
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.0+1
  flutter_bloc: ^8.1.5
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.6
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  toggle_switch: ^2.3.0
  table_calendar: ^3.0.9
  device_info_plus: ^9.1.2
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  connectivity_plus:
  shared_preferences: ^2.2.3
  permission_handler: ^10.4.5
  cached_network_image: ^3.3.1
  signature: ^5.5.0
  flutter_inappwebview: ^6.0.0
  image_cropper: ^5.0.1
  qr_code_scanner: ^1.0.1
  pod_player: ^0.2.1
  video_player: ^2.8.5
  flutter_html:
  html_unescape: ^2.0.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  document_viewer: ^0.0.1
  webview_flutter: ^4.5.0
  geolocator: ^11.0.0
  background_fetch: ^1.3.4
  flutter_osm_plugin: ^0.70.0
  package_info_plus: ^4.2.0
  searchable_listview:
  path: ^1.8.3
  open_file: ^3.3.2
  csv:
  flutter_document_picker: ^5.2.3
  flutter_html_to_pdf: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
