name: toolkit
description: ToolKitX is the latest end-to-end Software as a Service (SaaS) solution for field workforce management. We drive our customer's success by simplifying, automating and digitalizing their environment.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  intl:
  get_it:
  shimmer:
  encrypt:
  equatable:
  sqflite: ^2.3.2
  flutter_svg:
  file_picker: ^8.0.0+1
  flutter_bloc:
  hive_flutter:
  url_launcher:
  image_picker:
  path_provider:
  toggle_switch:
  table_calendar:
  device_info_plus: ^10.1.0
  json_annotation: 4.8.1
  cupertino_icons: ^1.0.2
  package_info_plus: ^7.0.0
  connectivity_plus:
  shared_preferences:
  permission_handler:
  searchable_listview: ^2.4.0
  cached_network_image:
  signature: ^5.4.0
  flutter_inappwebview: ^6.0.0
  image_cropper: ^5.0.1
  qr_code_scanner: ^1.0.1
  pod_player:
  video_player:
  flutter_html:
  html_unescape:
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  document_viewer: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^3.0.2
  json_serializable:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
