on:
  workflow_call:

jobs:
  checks:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Build Number
        id: increment-version
        run: |
          echo "Generating build number"
          build_number=$(TZ="IST" date +'%m%d%y%H%M')
          echo "::set-output name=version::$build_number"

      - name: Build Android app
        run: |
          echo "Building APK with build number: ${{ steps.increment-version.outputs.version }}"
          flutter build apk --release --build-number=${{ steps.increment-version.outputs.version }}

      - name: Rename build number
        run: |
          build_number=${{ steps.increment-version.outputs.version }}
          echo "Rename build number"
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk


      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: internal-testers
          file: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk


      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.increment-version.outputs.version }}.apk
          path: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk
