on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Generate Build Number
        id: increment-version
        run: |
          echo "Generating build number"
          build_number=$(TZ="IST" date +'%m%d%y%H%M')
          echo "::set-output name=version::$build_number"

      - name: Build Android app
        run: |
          echo "Building APK with build number: ${{ needs.checks.outputs.version }}"
          flutter build apk --release --build-number=${{ needs.checks.outputs.version }}

      - name: Rename build number
        run: |
          build_number=${{ needs.checks.outputs.version }}
          echo "Rename build number"
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${{ needs.checks.outputs.version }}.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: internal-testers
          file: build/app/outputs/apk/release/${{ needs.checks.outputs.version }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.checks.outputs.version }}.apk
          path: build/app/outputs/apk/release/${{ needs.checks.outputs.version }}.apk
