name: Build Android app
run: |
  echo "Building APK with build number: ${{ steps.increment-version.outputs.version }}"
  flutter build apk --release --build-number=${{ steps.increment-version.outputs.version }}
