name: Firebase App Distribution
uses: wzieba/Firebase-Distribution-Github-Action@v1
with:
  appId: ${{ secrets.FIREBASE_APP_ID }}
  token: ${{ secrets.FIREBASE_TOKEN }}
  groups: internal-testers
  file: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk
