on:
  workflow_call:

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: dart format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

      - name: Read current build number
        id: read-version
        run: |
          echo "Reading build number from version.txt"
          echo "version=$(cat version.txt))" >> $GITHUB_OUTPUT

      - name: Increment build number
        id: increment-version
        run: |
          echo "Incrementing build number"
          current_version=$(echo "${{ steps.read-version.outputs.version }}")
          incremented_version=$((current_version + 1))
          echo "::set-output name=version::$incremented_version"

      - name: Update build number
        run: |
          echo "Updating version.txt with new build number"
          echo ${{ steps.increment-version.outputs.version }} > version.txt

      - name: Build APK
        run: |
          echo "Building APK with build number: ${{ steps.increment-version.outputs.version }}"
          flutter build apk --release --build-number=${{ steps.increment-version.outputs.version }}

      - name: Rename APK with build number
        run: |
          echo "Renaming APK with build number"
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.increment-version.outputs.version }}.apk
          path: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk
