on:
  workflow_call:

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: dart format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

      - name: Read current build number
        id: read-version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Increment build number
        id: increment-version
        run: echo "::set-output name=version::$(( ${GITHUB_REF##*/} + 1 ))"

      - name: Build APK
        run: flutter build apk --split-per-abi --build-number=${{ steps.increment-version.outputs.version }}

      - name: Update build number
        run: echo ${{ steps.increment-version.outputs.version }} > version.txt

      - name: Rename APK with build number
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/${{ steps.increment-version.outputs.version }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.increment-version.outputs.version }}.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk