on:
  workflow_call:

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Run Flutter doctor
        run: flutter doctor


      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: dart format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk