name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  project-checks:
    uses: ./.github/workflows/project-check.yaml

  read-version:
    uses: ./.github/workflows/read-version.yaml

  build-apk:
    uses: ./.github/workflows/build-apk.yaml





