name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  project-checks:
    uses: ./.github/workflows/project-check.yaml

  upload-artifacts:
    uses: ./.github/workflows/upload-artifacts.yaml
    requires: [ project-checks ]



