name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: flutter format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

