name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/qa-checks.yaml

  build-android:
    needs: checks
    uses: ./.github/workflows/build-android.yaml
