name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checks:
    name: QA pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: dart format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

  build_android:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Build Number
        id: increment-version
        run: |
          echo "Generating build number"
          build_number=$(TZ="IST" date +'%m%d%y%H%M')
          echo "::set-output name=version::$build_number"

      - name: Build Android app
        run: |
          echo "Building APK with build number: ${{ steps.increment-version.outputs.version }}"
          flutter build apk --release --build-number=${{ steps.increment-version.outputs.version }}

      - name: Rename build number (Android)
        run: |
          echo "Rename build number"
          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk

  build_ios:
    needs: checks
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Build Number
        id: increment-version
        run: |
          echo "Generating build number"
          build_number=$(TZ="IST" date +'%m%d%y%H%M')
          echo "::set-output name=version::$build_number"

      - name: Build iOS app
        run: |
          echo "Building IPA with build number: ${{ steps.increment-version.outputs.version }}"
          flutter build ios --release --no-codesign --build-number=${{ steps.increment-version.outputs.version }}

      - name: Rename build number (iOS)
        run: |
          echo "Rename build number"
          mv build/ios/archive/Runner.ipa build/ios/archive/${{ steps.increment-version.outputs.version }}.ipa

  distribution:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: internal-testers
          file: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk

  artifact:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.increment-version.outputs.version }}.apk
          path: build/app/outputs/apk/release/${{ steps.increment-version.outputs.version }}.apk
