name: ToolKitX QA Workflow

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  checks:
    name: QA pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Check for formatting in the code
        run: dart format --set-exit-if-changed .

      - name: Analyze Static code
        run: flutter analyze .

  build:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-code
      - uses: ./.github/actions/generate-build-number
      - uses: ./.github/actions/build-android-app
      - uses: ./.github/actions/rename-build-number

  distribution:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-code
      - uses: ./.github/actions/firebase-app-distribution

  artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-code
      - uses: ./.github/actions/upload-apk-artifact
